db:
  image: postgres
  volumes:
    - "./db/data:/var/lib/postgresql/data"
    - "./db/init:/docker-entrypoint-initdb.d"

  ports:
    - "5000:5432"

  env_file:
    - db.env


app:
  build: .
  links:
    - db

  volumes:
    - "./app:/app"

  ports:
    - "3000:3000"

  env_file:
    - db.env
    - app.env

